/**
 * Complaint Flow Engine
 * Maps incident types to guidance data and manages flow logic
 */

import { otpFraudData } from '../data/otpFraud';
import { upiFraudData } from '../data/upiFraud';
import { phishingData } from '../data/phishing';
import { socialMediaHackData } from '../data/socialMediaHack';
import { fakeAppData } from '../data/fakeApp';

// Map incident IDs to their data
const guidanceDataMap = {
  'otp-fraud': otpFraudData,
  'upi-fraud': upiFraudData,
  'phishing': phishingData,
  'social-media-hack': socialMediaHackData,
  'fake-app': fakeAppData,
};

/**
 * Get guidance data for an incident type
 */
export const getGuidanceData = (incidentId) => {
  return guidanceDataMap[incidentId] || null;
};

/**
 * Generate complaint summary text
 */
export const generateSummary = (incidentId, answers) => {
  const guidance = getGuidanceData(incidentId);
  if (!guidance) return '';

  let summary = `Incident Type: ${guidance.title}\n\n`;
  
  // Add answers if provided
  if (answers && Object.keys(answers).length > 0) {
    summary += 'Details:\n';
    guidance.questions.forEach(q => {
      if (answers[q.id]) {
        summary += `- ${q.question} ${answers[q.id]}\n`;
      }
    });
    summary += '\n';
  }

  // Add immediate actions taken
  summary += 'Recommended Immediate Actions:\n';
  guidance.immediateActions.forEach((action, index) => {
    summary += `${index + 1}. ${action.action}\n`;
  });
  summary += '\n';

  // Add official resources
  summary += 'Official Resources:\n';
  guidance.officialLinks.forEach(link => {
    summary += `- ${link.name}`;
    if (link.url) summary += `: ${link.url}`;
    summary += '\n';
  });

  summary += '\n---\n';
  summary += 'Generated by CyberSakshar - Cyber Safety Platform\n';
  summary += 'This is guidance only. Please file official complaint at cybercrime.gov.in\n';

  return summary;
};

/**
 * Get next step in flow
 */
export const getNextStep = (currentStep, incidentId) => {
  const steps = [
    'intro',
    'type',
    'questions',
    'actions',
    'summary',
    'official',
  ];

  const currentIndex = steps.indexOf(currentStep);
  if (currentIndex === -1 || currentIndex === steps.length - 1) {
    return null;
  }

  return steps[currentIndex + 1];
};

/**
 * Get previous step in flow
 */
export const getPreviousStep = (currentStep) => {
  const steps = [
    'intro',
    'type',
    'questions',
    'actions',
    'summary',
    'official',
  ];

  const currentIndex = steps.indexOf(currentStep);
  if (currentIndex <= 0) {
    return null;
  }

  return steps[currentIndex - 1];
};

/**
 * Check if incident type is valid
 */
export const isValidIncidentType = (incidentId) => {
  return incidentId in guidanceDataMap;
};
