import React, { useState } from 'react';
import Button from '../../../components/Button';

const ReportDownload = ({ reportData }) => {
  const [downloading, setDownloading] = useState(false);

  const handleDownload = () => {
    setDownloading(true);

    // Generate text report
    const reportText = `
PERSONAL CYBER SAFETY REPORT
Generated by CyberSakshar

User: ${reportData.user.name}
Date: ${reportData.user.reportDate}

═══════════════════════════════════════

SAFETY OVERVIEW
Overall Safety Level: ${reportData.report.safetyLevel}
Current Risk Level: ${reportData.report.riskLevel}

RISK AREAS
${reportData.report.riskAreas.map(area => 
  `- ${area.name}: ${area.status.replace('-', ' ').toUpperCase()}`
).join('\n')}

PRACTICE SUMMARY
Simulations Attempted: ${reportData.data.simulations.attempted}
Simulations Completed: ${reportData.data.simulations.completed}
Scenarios: ${reportData.data.simulations.scenarios.map(s => s.name).join(', ')}

LEARNING COVERAGE
Modules Completed: ${reportData.data.learning.modulesCompleted}/${reportData.data.learning.totalModules}
Topics Covered: ${reportData.data.learning.topics.join(', ')}

READINESS INSIGHT
${reportData.report.insight}

RECOMMENDED NEXT STEPS
${reportData.report.nextSteps.map((step, i) => 
  `${i + 1}. ${step.title}\n   ${step.description}`
).join('\n\n')}

═══════════════════════════════════════

This report is for informational purposes only.
Continue practicing safe digital habits.

Generated by CyberSakshar - Cyber Safety Platform
    `.trim();

    // Create and download file
    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CyberSafety-Report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    setTimeout(() => setDownloading(false), 1000);
  };

  return (
    <div className="text-center">
      <div className="bg-blue-50 border-2 border-blue-200 rounded-xl p-6 mb-6">
        <p className="text-gray-700 mb-4">
          Download a copy of your safety report for your records
        </p>
        <Button
          onClick={handleDownload}
          disabled={downloading}
          className="px-8 py-3"
        >
          {downloading ? 'Generating...' : '💾 Download Safety Report'}
        </Button>
      </div>
      
      <p className="text-sm text-gray-600">
        This report is for informational purposes only and is not a certificate.
      </p>
    </div>
  );
};

export default ReportDownload;
